# Generated by Django 2.1 on 2018-09-25 03:20

from django.db import migrations, models
import permits.validators


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=9, unique=True, validators=[permits.validators.validate_number_car]),
        ),
    ]
